name: Deploy

run-name: Deploy ${{ inputs.gitRef || github.ref_name  }} to ${{ inputs.environment || 'integration' }}

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to deploy'
        required: true
        type: string
        default: 'main'
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  build-and-publish-image:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    name: Build and publish image
    uses: alphagov/govuk-infrastructure/.github/workflows/build-and-push-image.yml@main
    with:
      gitRef: ${{ inputs.gitRef || github.ref }}
    permissions:
      id-token: write
      contents: read
      packages: write
